services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: event_log_pipeline
      POSTGRES_USER: event_log_pipeline_user
      POSTGRES_PASSWORD: "000000"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U event_log_pipeline_user -d event_log_pipeline" ]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build: .
    depends_on:
      db:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/event_log_pipeline
      SPRING_DATASOURCE_USERNAME: event_log_pipeline_user
      SPRING_DATASOURCE_PASSWORD: "000000"
      SPRING_JPA_HIBERNATE_DDL_AUTO: create-drop
      CHART_OUTPUT_DIR: /app/charts
    ports:
      - "8080:8080"
    volumes:
      - ./images/charts:/app/charts

volumes:
  postgres_data: