apiVersion: v1
kind: Service
metadata:
  name: event-log-pipeline-service
spec:
  selector:
    app: event-log-pipeline
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP